import {
  PASSENGER_NAME_ALLOWED_CHARS_REGEX,
  PASSENGER_NAME_CONTAINS_DIGIT_REGEX,
  PASSENGER_NAME_MISPLACED_SPECIAL_REGEX,
  PASSENGER_NAME_SPECIAL_REGEX,
} from 'features/passengers/utils/validation/regex.ts';

export const PASSENGER_NAME_MIN_LENGTH = 2;
export const PASSENGER_NAME_MAX_LENGTH = 50;

export const PASSENGER_NAME_VALIDATION_RULES = {
  minLength: PASSENGER_NAME_MIN_LENGTH,
  maxLength: PASSENGER_NAME_MAX_LENGTH,
  containsDigit: PASSENGER_NAME_CONTAINS_DIGIT_REGEX,
  allowedChars: PASSENGER_NAME_ALLOWED_CHARS_REGEX,
  consecutiveSpecial: PASSENGER_NAME_SPECIAL_REGEX,
  misplacedSpecial: PASSENGER_NAME_MISPLACED_SPECIAL_REGEX,
};
